package.json

chore: build, deploy 관련 스크립트를 추가합니다.

---

.github/workflows/deploy.yml
buil.sh

chore: 개인 계정 래포에 연결합니다.

---

src/app/page.tsx

chore: pr 탬플릿- 테스트

---

package-lock.json
package.json
src/containers/timer/countdown/countdown-components/countdown-input.tsx
src/containers/timer/countdown/countdown-display/countdown-display.tsx
src/containers/timer/countdown/countdown-provider/countdown-provider.constants.ts
src/containers/timer/countdown/countdown-provider/countdown-provider.tsx

1. 1분 추가, 1분 감소 버튼 추가 
2. 60분이 넘으면 시간 input 추가
3. 최대 시간 9시간 59분 59초 설정
4. 분, 초 input에 최대 59까지 입력 가능
5. 시간, 분, 초 input 고정해서 보이기 
6. input의 기본 화살표 없애기 
7. isActive일 때 input의 수 readOnly로 설정
- countdown-providers에 변수와 함수를 추가했습니다.

feat: 타이머 1분 추가/감소 버튼, 시간 input, 최대 시간 설정을 구현합니다. 

---

src/containers/landing/menu-list/menu-list.tsx

verecl에 teachercan.com 도메인을 연결하여 기존에 사용하던 v1의 도메인이 변경되었습니다. 랜딩페이지의 '티처켄 V1' 버튼에 변경된 v1의 도메인 주소를 적용합니다.

feat: 티처켄 v1 url을 변경합니다.

---

src/containers/timer/countdown/countdown.tsx

refactor: countdown-tsx 오타 수정

---

src/app/qr-code/page.tsx
src/app/timer/page.tsx
src/containers/qr-code/qr-code-container.tsx

- QR 코드 페이지 추가
@jjswan 
기능 완성될 때까지는 랜딩페이지에 버튼을 만들면 안 되니 우선 페이지만 추가했어요!
로컬 서버에서 아래 주소로 접속하셔서 작업하시면 됩니다 :)
```
http://localhost:3000/qr-code
```
그리고 작업하실 때 [qrcode.react](https://www.npmjs.com/package/qrcode.react) 라이브러리 이 명령어로 설치하시고 진행해주세요~
```
yarn add qrcode.react
```
이전 PR과 `yarn.lock` 파일 충돌날 수 있을 것 같아서 제가 직접 설치하진 않았습니다 ㅎㅎ 이전 PR 머지되면 pull 받으시고 설치하시면 될 것 같아요!

feat(qr-code): QR 코드 기능을 개발할 페이지를 추가합니다.

---

src/containers/timer/countdown/countdown-display/colon.tsx
src/containers/timer/countdown/countdown-display/countdown-display.tsx
src/containers/timer/countdown/countdown-music-provider/countdown-music-provider.tsx
src/containers/timer/countdown/countdown-music/countdown-music.tsx
src/containers/timer/countdown/countdown-setting/countdown-setting.tsx
src/containers/timer/countdown/countdown-setting/setting-alarm/setting-alarm.tsx
src/containers/timer/countdown/countdown-setting/setting-music/setting-music.tsx
src/containers/timer/countdown/countdown-setting/setting-screen-size/setting-screen-size.tsx
src/containers/timer/countdown/countdown-setting/setting-time/setting-time.tsx
src/containers/timer/countdown/countdown.tsx

- 유튜브 공유 URL도 입력 가능하도록 추가
1. 유튜브 영상 주소창에서 URL 직접 복사
2. 영상 공유 버튼으로 URL 복사
3. 영상 우클릭 -> `동영상 URL 복사` 선택
- 각각 복사되는 URL이 조금씩 다름
- 기존에는 i 방법으로 복사한 URL만 입력 가능했으나 ii, iii 방법으로 복사한 URL도 입력 가능하도록 추가
- URL에서 video id 추출 방식 변경함에 따라 URL 유효성 검사 조건 수정
- 타이머 버튼과 타이머 배경음악 영역이 겹치는 문제 CSS 수정
- 타이머 창 크기별 반응형 스타일 추가
- 1/4 화면(반응형 모바일 사이즈)의 경우 시간, 재생/정지 버튼, 설정 버튼 외의 UI는 숨김 처리 및 전체화면 버튼을 별도로 노출

feat: 타이머에 유튜브 공유 URL 입력 추가 및 반응형 스타일을 추가합니다.

---

src/components/dialog.tsx
src/containers/qr-code/generator/generator-expansion/generator-expansion.tsx
yarn.lock

- shadcn에서 제공하는 dialog 코드를 바탕으로 dialog을 띄웁니다.

fix: dialog가 정상 동작하도록 fix합니다.

---

package.json
src/containers/qr-code/qr-code-container.tsx
src/containers/qr-code/qr-code-generator/qr-code-generator-debounce.tsx
src/containers/qr-code/qr-code-generator/qr-code-generator.tsx
src/containers/qr-code/qr-code-savelink/qr-code-savelink.tsx
yarn.lock

feat: qr 코드 생성 중 디바운스 기능을 추가합니다. 

---

src/containers/timer/countdown/countdown-display/countdown-display.tsx
src/containers/timer/countdown/countdown-provider/countdown-provider.tsx

feat:타이머 분, 초 버튼에 click and hold 기능을 추가합니다. 

---

package.json
src/containers/qr-code/qr-code-generator/qr-code-generator.tsx
yarn.lock

feat: qrcode QR코드를 북마크할 때 아이디를 저장하여 북마크된 QR코드를 하나씩만 삭제합니다.  

---

src/components/card.tsx
src/containers/landing/dDay-list/dDay-list.tsx
src/containers/landing/landing-container.tsx
src/hooks/useLocalStorage.ts

feat: 메인페이지에 디데이 기능을 추가합니다. 

---

src/containers/music-request/music-request-student/music-request-student-container.tsx

Failed to compile.
./src/containers/music-request/music-request-student/music-request-student-container.tsx:9:11
Type error: Cannot find name 'MusicRequestStudentParams'.
7 |   params,
8 | }: {
>  9 |   params: MusicRequestStudentParams;
|           ^
10 | }) {
11 |   return (
12 |     <div>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
버셀에서 빌드중에 위와 같은 에러가 발생해서 수정하였습니다.

feat: 배포중 발견된 오류(import 누락)를 수정합니다.

---

vercel.json

NextJS서버에서 router handler를 통해 api를 요청하게 되는 경우 CORS 오류가 뜹니다. 이를 해결합니다. 해결 방법은 vercel 공홈 문서를 참고하였습니다. 
next.config.js에 추가를 하여도 되지만 vercel를 사용하고 있어 vercel.json 설정을 통해 해결할 수 있는 방법이 있어 이를 적용하였습니다.
How can I enable CORS on Vercel? - https://vercel.com/guides/how-to-enable-cors#enabling-cors-using%C2%A0vercel.json

fix: vercel 서버에서 cors 오류 해결

---

.env
package.json
src/containers/landing/dDay-list/dDay-list.tsx
src/containers/landing/lunch-menu/lunch-menu.tsx
src/hooks/useLocalStorage.ts
yarn.lock

feat: 학교 식단 조회 기능을 추가합니다. 

---

package.json
src/containers/landing/welcome/welcome.tsx
yarn.lock

서버의 시간이 한국시간과 달라 엉뚱한 인사말이 보여집니다. 이를 해결합니다.

fix: 한국 시간 기준으로 인사말을 보여줍니다.

---

package.json
src/app/layout.tsx
yarn.lock

구글 GA를 추가합니다. 아직 버튼 클릭 이벤트와 같은 구체적인 이벤트는 추가하지 않았습니다.

feat: 구글 애널리틱스를 추가합니다.

---

src/app/api/youtube/video/title/[videoId]/route.tsx

feat: videoId 못 찾는 문제를 해결합니다.

---

src/containers/landing/history/recently-visited/recently-visited.tsx

유효하지 않는 경로인 경우 title, Icon이 없기 때문에 버그가 발생합니다. 때문에 이 전에 유효성을 검사하고 null를 return합니다.

fix: 유효하지 않는 경로인 경우 최근방문페이지를 보여주진 않습니다.

---

src/apis/music-request/musicRequest.ts
src/app/layout.tsx
src/components/header/header.tsx
src/components/navigation/navigation.tsx
src/containers/music-request/music-request-student/music-request-student-container.tsx
src/containers/music-request/music-request-student/music-request-student-main/create-name-page/create-name-page.tsx
src/containers/music-request/music-request-student/music-request-student-main/music-request-student-main.tsx
src/containers/music-request/music-request-student/music-request-student-main/search-page/search-page.tsx
src/containers/music-request/music-request-teacher/music-request-teacher-main/music-list/music-card/music-card.tsx
src/containers/music-request/music-request-teacher/music-request-teacher-main/music-refresh/music-refresh.tsx
src/containers/music-request/music-request-teacher/music-request-teacher-main/music-request-teacher-main.tsx
src/containers/music-request/music-request-teacher/music-request-teacher-main/student-list/student-list.tsx

- 학생 응답값이 바뀌어 이를 수정합니다.
- 학생 음악 신청 페이지의 네이게이션 헤더를 제거합니다.
- 음악 신청 Tabs의 모바일 스타일을 수정합니다.
- 재생 중인 곡 삭제를 금지합니다.
- refetching 문제를 해결합니다.

feat: 음악신청 디테일을 수정합니다.

---

src/app/api/lunchmenu/meal-data/route.ts
src/containers/landing/landing-container.tsx
src/containers/landing/lunch-menu/allergy/allergy.tsx
src/containers/landing/lunch-menu/allergy/allergyContext.tsx
src/containers/landing/lunch-menu/lunchmenu-search/schoolSearchDialog.tsx
src/containers/landing/lunch-menu/lunchmenu-search/useMealData.ts
src/containers/landing/lunch-menu/lunchmenu.tsx
src/containers/landing/lunch-menu/mealInformation/mealItem.tsx
src/containers/landing/lunch-menu/mealInformation/mealList.tsx
src/hooks/useLocalStorage.ts

feat: 점심 식단에 알러지 정보를 추가합니다. 

---

package.json
src/apis/feedback/feedbackRequest.ts
src/apis/fetcher.ts
src/apis/music-request/musicRequest.ts
src/app/api/notion/feedback/route.ts
src/app/feedback/page.tsx
src/components/dialog.tsx
src/components/header/header.tsx
src/components/navigation/navigation.tsx
src/constants/route.ts
src/containers/feedback/feedback-container.tsx
src/containers/feedback/feedback-form/feedback-form.hooks.ts
src/containers/feedback/feedback-form/feedback-form.tsx
src/containers/feedback/feedback-result/feedback-result.tsx
src/containers/landing/history/recently-visited/link-card/link-card.tsx
src/containers/landing/history/recently-visited/recently-visited.tsx
src/hooks/apis/feedback/use-create-feedback.tsx
src/hooks/apis/music-request/use-get-music-request-room-title.ts
src/hooks/apis/music-request/use-get-music-request-room.ts
src/hooks/use-recently-visited.ts
yarn.lock

피드백 페이지를 구현합니다.
1. 피드백을 작성할 수 있습니다.
2. 작성된 피드백 페이지에 접근하여 진행상태를 확인할 수 있습니다.
간단한 피드백을 받고 음악신청 메뉴 오픈과 함께 배포하려고 합니다.
아래는 노션페이지로 이후 회의 때 정리해서 말씀드리겠습니다.
---
회의 때 받은 피드백을 바탕으로 이메일을 입력받을 수 있도록 하고 피드백 주소는 제거하였습니다.

feat: 피드백 페이지를 구현합니다.

---

src/containers/landing/lunch-menu/allergy/allergy.tsx
src/containers/landing/lunch-menu/lunchmenu.tsx

feat: 학교가 등록되지 않았을 때 알러지 기능이 보이지 않게 합니다. 

---

src/containers/music-request/music-request-teacher/music-request-teacher-main/music-list/music-card/music-card.tsx
src/containers/music-request/music-request-teacher/music-request-teacher-main/room-info/room-info.tsx

feat: 음악 신청 예시 페이지를 위한 작업을 진행합니다.

---

src/containers/music-request/music-request-container.tsx

현재 음신 청 서비스의 서버를 점검중에 있어 서비스 이용이 어렵습니다. 때문에 음악 신청 서비스 점섬 텍스트를 노출합니다.

feat: 음악 신청 서비스 점검 텍스트 노출

---

src/app/api/youtube/video/[videoID]/route.tsx
src/containers/timer/countdown/countdown-setting/setting-music/setting-music.tsx

1. 타이머 실행시 볼륨조절이 막히는 버그
2. 배경음악 검색기능 추가
3. 음악 검색 개수 추가
1. 타이머 실행시 볼륨조절이 막히는 버그
코드 1줄 삭제로 해결~!
_____________________________________________________________________________________________
2. 배경음악 검색기능 추가
유투브 주소를 입력할 경우 기존과 변함없음
검색어를 입력할 경우
유투브로 음악을 검색함. 검색창에서 새로운 검색어를 입력가능
[적용] 버튼을 누르면 배경음악으로 설정완료~!
_____________________________________________________________________________________________
유투브 검색 갯수가 넘 적어서 9개로 쿼리를 바꿔두었습니다~!

feat: 볼륨조절이 막히는 버그를 수정합니다.

---

src/app/setting/page.tsx
src/containers/landing/lunch-menu/allergy/allergy.tsx
src/containers/landing/lunch-menu/mealInformation/mealItem.tsx
src/containers/setting/font-size-setting/font-size-setting.tsx
src/containers/setting/screen-mode-setting/screen-mode-setting.tsx
src/containers/setting/setting-container.tsx
src/utils/getCookieValue.ts

- 설정페이지에서 쿠키의 값을 읽어오는 과정에서 서버에서 그린 UI와 클라에서 그린 UI가 불일치하여 사용자가 설정한(쿠키값에 있는 설정 값)이 반영이 되지 않는 문제가 있습니다. 이를 해결합니다.
- 식단표에 다크/라이트 모드가 적용되지 않았던 부분을 추가합니다.

fix: 설정 페이지 상태 업데이트와 식단표 라이트/다크 모드를 수정합니다.

---

src/containers/notice-suggestion/notice-suggestion.constants.ts

- 알림장 문구 추천 `어버이날` 카테고리 삭제
어버이날이 끝났으므로 시즌 한정 카테고리를 삭제합니다.

feat: 알림장 문구 추천 "어버이날" 카테고리를 삭제합니다.

---

src/containers/music-request/music-request-container.tsx

feat: 음악신청 방 목록 초기화 버튼 추가

---

src/containers/routine-timer/routine-timer-list.tsx

fix: 타입 반영

---

src/constants/route.ts
src/containers/landing/history/recently-visited/recently-visited.tsx

fix: 루틴타이머를 숨기고 최근 방문 페이지 최소 높이를 추가합니다.

---

src/apis/music-request/musicRequest.ts
src/containers/music-request/music-request-teacher/music-request-teacher-main/music-list/music-card/music-card.tsx
src/containers/music-request/music-request-teacher/music-request-teacher-main/music-player/music-player-bar/music-player-bar.tsx

fix: 음악신청 학생이름 타입명 수정

---

src/containers/timer/countdown/countdown-setting/setting-time/setting-time.tsx

feat: 타이머 60분 시간 증감 버튼을 30초로 수정합니다. 

---

src/app/roulette/page.tsx
src/constants/route.ts

feat: 룰레 돌리기 페이지를 공개합니다.

---

src/constants/route.ts
src/containers/announcement/announcement-detail/announcement-detail.tsx
src/containers/announcement/announcement-detail/image-with-skeleton.tsx

feat: 공지사항 이미지 영역을 개선하고 룰렛 돌리기 new 뱃지를 추가합니다.

---

src/containers/roulette/roulette-container.tsx
src/containers/roulette/roulette-input/roulette-input.tsx
src/containers/roulette/roulette-result/roulette-result.tsx
src/containers/roulette/roulette-wheel/roulette-wheel.tsx

1. 룰렛 항목 빠르게 만들기
2. 전체적으로 다크모드 추가

feat: 룰렛 돌리기 빠른 아이템 설정 기능을 구현합니다.
